version: '3'

services:
  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    environment:
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: my-topic
    depends_on:
      - kafka
    networks:
      - kafka-net

