version: '3'

services:
  consumer:
    image: kafka-bench-consumer:latest
    environment:
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: people
    depends_on:
      - kafka
    networks:
      - kafka-net
