FROM golang:1.19-alpine
RUN apk update && apk add git
COPY ./ /go/src/consumer/
WORKDIR /go/src/consumer
RUN go mod vendor
RUN go build -o consumer app/cmd/consumer.go
ENTRYPOINT ["/go/src/consumer/consumer"]