FROM golang:1.19-alpine
RUN apk update && apk add git
COPY ./ /go/src/producer/
WORKDIR /go/src/producer
RUN go mod vendor
RUN go build -o producer app/cmd/producer.go
ENTRYPOINT ["/go/src/producer/producer"]


